### PR TITLE
daemon-rpc: Document new get_info response fields

### PR DESCRIPTION
**Pull request by ndorf**
Just getting started on this work; wanted to publish it sooner rather than later in order to get early feedback and/or avoid others duplicating effort. Please don't merge until WIP tag is removed :)

### CODE REVIEW

**Comment by erciccione** [comment]
Awesome, thanks. let me know if you need anything :)

**Comment by erciccione** [comment]
Hey @ndorf any news about this? Would be good to have https://github.com/monero-project/monero-site/pull/1448 ready soon :)

**Comment by ndorf** [comment]
Sorry, got unexpectedly busy with other stuff. I'll make some progress on this in the next few days.

**Comment by erciccione** [comment]
@ndorf maybe we should just add these definitions and then add more in the future?

**Comment by ndorf** [comment]
Updated with 2/4 fields and rebased. Let me see if I can figure out what the other 2 mean real quick so at least this one endpoint can be complete.

**Comment by erciccione** [comment]
@ndorf the PR got messed up, probably better to make a new one :)

**Comment by ndorf** [comment]
How's that?

**Comment by erciccione** [comment]
Looks good. Thanks :)

Merging. Maybe some of these definitions can be reused elsewhere.

**Pull request merged**
